### ISSUE TITLE
First example in the JOSS paper and the structure of the package

### ISSUE THREAD

**Issue by emptymalei** [berenslab/MorphoPy#104]
Thanks for this nice package. It is definitely very useful to anyone whoever has done the painful manual labor on determining the statistics. 😄 

I am running into this problem regarding ~the installation process~ the first example in the paper. Would you mind looking into it? 😃 

## What was tested

My platform:

1. OS: macOS High Sierra
2. Python: conda 4.8.0, python 3.5

I did the following:

1. Create a python 3.5 env: `conda create -n morphopy3.5 python=3.5 pip`
2. Install morphopy 0.6 in this env: `pip install morphopy`
3. `import MorphoPy.NeuronTree as nt` fails. I am following the demo [here](https://github.com/openjournals/joss-papers/blob/joss.02339/joss.02339/10.21105.joss.02339.pdf).

Here is the [link to the screencast](https://asciinema.org/a/r2dXMvNy8Q1WiogTclnBBc37f) showing the results.

[![asciicast](https://asciinema.org/a/r2dXMvNy8Q1WiogTclnBBc37f.svg)](https://asciinema.org/a/r2dXMvNy8Q1WiogTclnBBc37f)

In the screencast, we will see that we have no modules named `morphopy` or `MorphoPy`. Instead, we have `computation` and `neurontree`.

On the other hand, a small tweak of the example code [in the paper](https://github.com/openjournals/joss-papers/blob/joss.02339/joss.02339/10.21105.joss.02339.pdf) can make it work just fine.

```
import matplotlib.pyplot as plt
from computation import file_manager as fm
import neurontree as nt
from neurontree.plotting import show_threeview

N = fm.load_swc_file("~/Downloads/204-2-6nj.swc")
Dendrites = N.get_dendritic_tree()


fig = plt.figure(figsize=(10,10))
show_threeview(N, fig)
```

Maybe `import MorphoPy.NeuronTree as nt` is some legacy code?

## Why are `computation` and `neurontree` treated as top-level modules

The folder structure of this package is a bit different from the commonly used ones. As the folders `computation` and `neurontree` are top-level folders, they will be at the same level as other packages after installation, as shown in the above screencast.

I am not sure ~if this is by design~ why the package is designed in this way or maybe I missed the point. 

If I may make any suggestions, I am used to a folder structure that has a folder `morphopy` with modules `computation` and `neurontree` in it. 😄 

```
.
├── Creating\ density\ maps.ipynb
├── LICENSE
├── README.md
├── ...
├── morphopy
│    ├── MorphoPy.py
│    ├── __init__.py
│    ├── computation
│    └── neurontree  
├── ...
└── ...
```

In this way, we will be able to `import morphopy.neurontree as nt` so that we won't interfere with modules in other packages since `computation` is kind of a generic module name. 

Thank you very much for your time! Have a nice day! 🌞

**Comment by oliviaguest** [comment]
Just a reminder, ignore if not applicable, that the bulk of the review (unless super technical) should be at: https://github.com/openjournals/joss-reviews/issues/2339 — thanks. ☺️

**Comment by Visdoom** [comment]
Hi @emptymalei , 

thank you for being so thorough with the review. 
This package structure is indeed a bit of legacy code and was kept because we did not want the file paths for the installation of the command-line tool. However, we agree that it is confusing and will change it as you have proposed. 

@avdaranyi as we discussed, I will create the necessary folder structure and update all notebooks and code snippets. Once this is done, you can check and update the installation of the tool.

**Comment by Visdoom** [comment]
@avdaranyi The folder structure is updated. Now you can go in and update the installation. 
You can find the code in the branch https://github.com/berenslab/MorphoPy/tree/change_folder_structure

**Comment by avdaranyi** [comment]
The new folder structure is also adapted in the command line tool. "MorphoPy.py" needs to be outside of the package, because it is not part of it and only an external script file, which calls the package. So I moved it back outside. The next release will contain all changes.

**Comment by emptymalei** [comment]
@avdaranyi 

I have some ideas, if I may. 😄 

Would it make sense to use the `console_scripts` approach instead of `scripts` approach? 

Folder structure:

```
.
├── Creating\ density\ maps.ipynb
├── LICENSE
├── README.md
├── ...
├── morphopy
│    ├── MorphoPy.py
│    ├── __init__.py
│    ├── computation
│    └── neurontree  
├── ...
└── ...
```

In `setup.py`

```
setup(
    ...
    entry_points = {
        'console_scripts': ['morphopy=morphopy.MorphoPy:main'],
    }
    ...
)
```

Then we can use the command `morphopy` in the terminal.

I never used the `scripts` approach but I know the `console_scripts` approach works when you need to import the package itself. Besides, the `console_scripts` approach also allows us to use the command line script in the actual python code.

**Comment by avdaranyi** [comment]
Hi @emptymalei 

thank you for the suggestion. I think that's a very good idea. And on Windows an "exe"-file will be created which makes it easier to install there. With this approach I can run the command line script in python like this:

```
import morphopy.MorphoPy
morphopy.MorphoPy.main(['arg1', 'arg2', ...])
```

Thats also nice but do you know how can I run it on the command line without installing it?

If I'm inside the GitHub repository and want to test the command line tool outside of python then all imports will fail. So if I change it like this, I always have to switch to python command line and need to import the package first. That would make the testing a little bit ugly, also because I don't have the batch history and completion there.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by emptymalei** [comment]
@avdaranyi That's a good question. I don't really know how to do such tests except installing the package every time. :stuck_out_tongue:

On the other hand, this is not the most standard test in python. One possible solution is to write some `nose` tests and test the command line script. Then one only needs to do `nosetests` to test the script. I personally find the most useful tools to build a command-line tool is [`click`](https://click.palletsprojects.com/en/7.x/) which ships [runners to test the command-line tool itself](https://click.palletsprojects.com/en/7.x/testing/?highlight=test). This is only some personal experience.
