### ISSUE TITLE
Some suggestions for the README file

### ISSUE THREAD

**Issue by mstimberg** [berenslab/MorphoPy#106]
(Issue opened as part of openjournals/joss-reviews#2339)

I found a few minor issues in the `README.md` file:
* Usage: "Just call everywhere..." sounds a bit odd, maybe "From anywhere, you can simply call.." or something similar?
* Citing MorphoPy: this should ideally more specific (telling the user exactly how to cite), but then I think this is what the JOSS paper is for :smile:
* Density maps: the function is misspelled as `compute_denisty_maps()` (same typo in the tutorial)
* Module description: it states that "If several soma points are present in the reconstruction file they will be automatically collapsed to the centroid of their convex hull on file loading", but I think this is only the case for > 3 points since MorphoPy also supports the 3-point soma format?
* Persistence: the text mentions how to implement custom persistence distance functions, but does not mention that if you use the API, you can directly provide this function as an argument. Inserting the function by editing a source file in the tool itself is not a great solution (most users won't even know where this file is after installing it with `pip`), but I completely understand that it would be quite an effort to make this work for the command line tool in another way.

**Comment by Visdoom** [comment]
@mstimberg 
thanks for all the thorough read of our README. In the following we list what we have changed. 
1.  "Just call everywhere..." has been changed to "After the installation you can simply call"
2. The Citation paragraph now features a specific bibtex item. We will update it to the JOSS reference once this paper has been published.
3. typo is fixed
4. MorphoPy does not support the 3-point soma format (yet). When 2-3 points are present then their mean location is computed and taken as the soma. We updated the text accordingly.
5. We agree that writing into source files is not optimal but we decided to wait for the feedback of the community to see if that option is really used. We now mention the API option specifically.

With these updates we hope that it is fair to close this issue.

**Comment by mstimberg** [comment]
> With these updates we hope that it is fair to close this issue.

I agree, all changes look good from my side.

**Comment by mstimberg** [comment]
Oh, except that I just realized that it still uses `compute_denisty_maps()` instead of `compute_density_maps()`

**Comment by Visdoom** [comment]
Are you sure? When I check in the repo I cannot see the typo: 
https://github.com/berenslab/MorphoPy/blob/bd8a198d28e89197958d380e34ebf38f91d156e7/morphopy/computation/feature_presentation.py#L161

**Comment by mstimberg** [comment]
I meant in the README (sorry, there does not seem to be a better way to link to specific lines in a markdown file):
https://github.com/berenslab/MorphoPy/blame/master/README.md#L214

The same typo is also in the tutorial (section "Computing Density Maps")
