### ISSUE TITLE
File naming for density output

### ISSUE THREAD

**Issue by Visdoom** [berenslab/MorphoPy#111]
Hi @avdaranyi, 

while writing the tests I realised that the output filenames for the density maps contain the filename twice.
When I run the command:
`./MorphoPy.py -c density -i ../data/EC3-80604.CNG.rotated.swc -o ../tests/test_data/`
the output file for the density data is called `EC3-80604.CNG.rotated.swc_density_EC3-80604.CNG.rotated.swc_reconstruction_density.mat`.

I propose to change the naming such that we have `filename_density.[png|mat]`. This way the naming is as short as possible and the two files (plot and data) are distinguishable through their file endings.

**Comment by avdaranyi** [comment]
Hi @Visdoom ,
the doubled filename is a bug after the change of the input handling. I already solved it, but isn't uploaded. I will upload it soon. But should I really kick out the bin_sizes of the filename? It was a really big thing to do it this way and I think, if you are making various outputs with different bin sizes, it would be nice to have a way to distingush the files.

**Comment by Visdoom** [comment]
@avdaranyi  You are right, we should keep the bin sizes in the names. I just think we do not need different names for the png and the mat files, since they are distinguishable by their file ending.

**Comment by Visdoom** [comment]
@avdaranyi Can I close this?
