### ISSUE TITLE
Automatically relabel node ids when loading a file in?

### ISSUE THREAD

**Issue by Visdoom** [berenslab/MorphoPy#116]
When a file is read in we do some processing steps (like removing duplicate points) that might lead to a inconsistency between node labels and actual number of nodes in the neuron tree object. E.g. in this case we can have a node id that is higher than the number of points we have. This can be confusing to the user. 
Should we call the function `rename_nodes()` in the end of the constructor? This would relabel all nodes consecutively. However, then the node ids do not necessarily correspond to the ones in the original swc file any more which in turn can lead to confusion.

I'd like your opinion on that. Add a paragraph about it to the repo? Do the 'hidden' relabeling of nodes? Do nothing?

**Comment by huangziwei** [comment]
@Visdoom Hi Sophie, are you still planning to do this?

**Comment by huangziwei** [comment]
Close due to inactive. But feel free to reopen it whenever you see fit.
