### ISSUE TITLE
 A problem with the method "smooth_neurites( )"

### ISSUE THREAD

**Issue by Thinknoon** [berenslab/MorphoPy#118]
There is a problem when call the method "smooth_neurites( )", How could I fit this problem?  The version of  MorphoPy is 0.7.1 and the version of networkx is 2.5. we really appreciate your help ^_^
![problem_1](https://user-images.githubusercontent.com/55904459/123277605-d8603280-d538-11eb-8aaa-90f7a48e0761.PNG)

**Comment by philippberens** [comment]
We will be looking into that

**Comment by huangziwei** [comment]
fixed by #125 . please try pull the latest commit from the master branch.
