### ISSUE TITLE
version on PyPI is not up-to-date.

### ISSUE THREAD

**Issue by huangziwei** [berenslab/MorphoPy#119]
E.g. the networkx version bug has been fixed on the master branch but not in the PyPI version.

**Comment by yzx9** [comment]
Vote!

BTW: fix `networkx` version conversion [b02ec5](https://github.com/berenslab/MorphoPy/commit/b02ec5de5d55e1e444ca635f33c601c89417f6f5#diff-a1ea34fed299c026df2b7df6013c82cdca84bad135006fbdf8da9ea856f31656R68)

**Comment by huangziwei** [comment]
The PyPI version is now up-to-date (v0.7.2).
