### ISSUE TITLE
Hi How can I solve this issue~ Thanks!

### ISSUE THREAD

**Issue by melancholy12** [berenslab/MorphoPy#127]
File D:\Python\Python310\lib\site-packages\morphopy\computation\file_manager.py:40, in check_neurontree(neurontree)
     38     raise ValueError('Graph has no root defined!')
     39 if not neurontree.is_connected():
---> 40     raise ValueError('Graph has disconnected nodes!')

ValueError: Graph has disconnected nodes!

**Comment by huangziwei** [comment]
This error means that your swc file contains disconnected neurites, that is, some neurites are not connected to any other neurites or soma. You need to fix that before using MorphoPy.

**Comment by melancholy12** [comment]
I think there is nothing wrong when I used the Neurolucida for reconstruction.
Can I solve this issue by using python packages? Just remove the disconnected nodes or neurites?

**Comment by huangziwei** [comment]
MophoPy doesn't handle this use case right now. But I can have a look if you provide some example data.

**Comment by melancholy12** [comment]
Could I send you from an email? (Thanks for your time for helping)

**Comment by huangziwei** [comment]
you can send it to the email address on my Github Profile.
