### ISSUE TITLE
What is the difference between get_local_vector and get_remote_vector?

### ISSUE THREAD

**Issue by Visdoom** [berenslab/MorphoPy#81]
The description of both functions is exactly the same. The only difference is one index. Can we come up with a more descriptive name for those functions?

**Comment by huangziwei** [comment]
I thought I changed the doc but in fact I just copy-and-paste... Fixed. 

get_local_vector: the vector between first and second point of the path
get_remote_vector: the vector between first and last point of the path

maybe we should come up with better variable names.
